<def f='include/llvm-6.0/llvm/Support/Error.h' l='298' ll='303' type='std::unique_ptr&lt;ErrorInfoBase&gt; llvm::Error::takePayload()'/>
<use f='include/llvm-6.0/llvm/Support/Error.h' l='384' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-6.0/llvm/Support/Error.h' l='389' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-6.0/llvm/Support/Error.h' l='395' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-6.0/llvm/Support/Error.h' l='399' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-6.0/llvm/Support/Error.h' l='399' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-6.0/llvm/Support/Error.h' l='448' u='c' c='_ZN4llvm8ExpectedC1ENS_5ErrorE'/>
<use f='include/llvm-6.0/llvm/Support/Error.h' l='870' u='c' c='_ZN4llvm12handleErrorsENS_5ErrorEDpOT_'/>
